### ISSUE TITLE
How about adding a capture function for each browser window?

### ISSUE THREAD

**Issue by kdh8219** [bozbez/win-capture-audio#141]

**Comment by DwarfFighterCleric** [comment]
Unfortunately the only way of making that possible for now is having a separate browser that you have to load up for things that you specifically want to be recorded.  
Also it's the only practical way of achieving this on Linux (because either if you use different Sinks on pulseaudio, every new tab you open or everytime you Refresh a page, that page will be loaded into that sink as well, resulting in things you didn't want to be recorded being recorded... lots of manual labor... easier to setup a different browser just for that task)

**Comment by bozbez** [comment]
Chrome has an in-browser API for per-tab capture but AFAIK there is no way to use this from the outside. There is no other feasible way to do this as (chrome-based and firefox at least) browsers internally mix all of their audio to a single output stream.

Pre-2.2.2 you could probably manage this by launching separate actual browser instances (not just windows), but reliably re-matching these windows based on title information proved to be too fragile.
