### ISSUE TITLE
[Discussion] Future of this plugin(OBS 28.0 includes app audio capture)

### ISSUE THREAD

**Issue by pcislocked** [bozbez/win-capture-audio#208]
The upcoming OBS release 28 includes application audio capture natively. I'm not sure if it's this plugin embedded into the main release or another implemention, either way it seems unclear what's going to happen to this repo. Just curious and wanted to ask everyone

**Comment by TheGinGear** [comment]
Personally, I will still be using this until OBS functions EXACTLY like this; with the ability to group a bunch of programs into one volume slider/output. It's a huge convenience not having a bajillion audio sources/sliders sometimes. A different plugin being able to do sort of the same thing would make this redundant then, but for now being able to continue using my setup without having to remake it into a bunch of tiny separate ones would be nice.

**Comment by RandomNerd1** [comment]
> Personally, I will still be using this until OBS functions EXACTLY like this; with the ability to group a bunch of programs into one volume slider/output. It's a huge convenience not having a bajillion audio sources/sliders sometimes. A different plugin being able to do sort of the same thing would make this redundant then, but for now being able to continue using my setup without having to remake it into a bunch of tiny separate ones would be nice.

Are you using this plugin in OBS 28 presently? I'm afraid to update to the new version without being absolutely certain this plugin will continue to work, as it has been game-changing for me as a streamer, and I am NOT willing to do without it, lol

**Comment by selvex** [comment]
Same! Reluctant to update cause setting audio sources up was a lot of work, and will be again.

**Comment by selvex** [comment]
Just found this: https://obsproject.com/kb/obs-studio-28-plugin-compatibility
According to OBS, should work.

**Comment by RandomNerd1** [comment]
Can someone confirm definitively who's upgraded, or can we get official word from the plugin author? :D

**Comment by aquazor** [comment]
> Can someone confirm definitively who's upgraded, or can we get official word from the plugin author? :D

I installed the newest OBS 28.0.1 and there is no built-in application audio capture thing. Also tried to install the plugin but it doesn't work either...

**Comment by TheGinGear** [comment]
@RandomNerd1 I can confirm it works just fine, using the latest version of OBS on windows 11.
@aquazor that sounds like it's a your setup specific issue, try making sure all your audio devices, channels, and monitor devices are set correctly, both in windows settings, OBS settings, and OBS Advanced Audio Properties.

**Comment by aquazor** [comment]
@TheGinGear 

I decided to check if my windows 10 version matches the requirements and found out that it doesn't. Gotta update it :/ Thanks for the tip

**Comment by ghost** [comment]
There's a few things to unpack here...
- First off, the native feature is marked BETA so if there are features we think are "missing" we should go report that upstream to OBS.
- This plugin consumes a Windows 11 API in a specific way. This functionally works on late versions of W10 but it's not supported by either Microsoft or OBS. So for comparison:
  - Does the new OBS native approach use the same API?
  - What is the OBS approach to supporting Windows 10?
  
- Grouping several input audio streams under one slider seems like it should be achievable using Source groups. If OBS gave a Groups an audio slider, that would deliver the feature @TheGinGear is asking for. Completely agree that the ability to say *this* slider controls the overall for *that* composited video stream makes all kinds of sense.

I can't actually figure out how GinGear has done that using this plugin but I don't think that matters for this discussion :-)

- This plugin also has the features:
  - capture all audio *except* the nominated application window
  - choosing the target window by using a hotkey
 which are both pretty amazing and aren't in OBS native yet.
 
 And finally there's the constraint which forced OBS to release 28 in the first place, which is QT5 is going out of support. I don't know if this plugin consumes QT5 directly anywhere or uses an OBS wrap, but if it does use QT directly, that's another issue for the roadmap. 

Meanwhile - this plugin is still working just fine on OBS 28.0.1, even though it's the latest Windows 11 Insider build, I have VB-cable installed, and I have load of other junk related to Cakewalk by Bandlabs installed.

**Comment by bozbez** [comment]
> Does the new OBS native approach use the same API?

Yes, it's basically a remix of the v2.1.0 version of this plugin integrated into win-wasapi.

> I can't actually figure out how GinGear has done that using this plugin but I don't think that matters for this discussion :-)

Just add multiple executables to the input list and they will be mixed internally by the plugin and volume controlled using the single source volume slider.

> ... capture all audio except the nominated application window

The API itself actually has a switch for exclude mode, but this doesn't work if you want to exclude multiple. The plugin re-implements this using its internal mixing so it _does_ support exclude multiple.

> ... choosing the target window by using a hotkey

This is super easy to implement and I can't believe they didn't bother including it for 28.0.

> I don't know if this plugin consumes QT5 directly anywhere or uses an OBS wrap ...

It uses the OBS plugin properties window API wrap, it isn't linked directly against QT at all.


The problem with the new support in win-wasapi is that it ignores the developments I've had to do to force this plugin to work with the audio session API rather than using window enumeration, and is written in a way that pretty much prohibits them from replicating that without great effort.

This means that it is pretty much bound to always use window enumeration selection and the many drawbacks that brings. This is pretty annoying for everyone since I can't just deprecate this plugin as I'd like and leaves users deciding whether they can get away with using the built in support or having to install a third-party plugin.

As for why this plugin hasn't just been merged into OBS, or why I wasn't consulted on any of the developments or issues with the API is a question you must ask to the OBS maintainers.

**Comment by ghost** [comment]
Great reply, thank you! (And great plug-in, obviously. I agree it's pretty grim that nobody approached you. It is supposed to be the open-source *community* after all.)

So the short answer to OP is:
- The plugin will stay around, because it implements advanced functionalities that are not available in native.

And could I make a request for the backlog - improve the discoverability of that feature which allows you to add multiples to one mixer?

**Comment by selvex** [comment]
Upgraded to 28 days ago and works flawlessly if anyone is still waiting for confirmation on that.

**Comment by FeedTheChunk** [comment]
I tried on V 28 yesterday and it did not work.  OBS through an error and said that it had to be removed.  I downgraded OBS V27 and it seems to work as expected.

**Comment by Ufinexa** [comment]
Attempted to use this plugin on my friends OBS 28, and it intermittently crashed (one crash for every 2 opens) as well as crashing mid stream. Once we removed the plugin all was okay again. So not quite sure what could be causing that.

**Comment by PlavorSeol** [comment]
There was a conversation in OBS Community server after I referenced this issue in there while back.
![obs-devs-excuse-1](https://user-images.githubusercontent.com/43488966/191742964-4998ae68-e079-4b62-aae6-08f71fc2448b.png)
![obs-devs-excuse-2](https://user-images.githubusercontent.com/43488966/191742972-0dfdc2d3-6f3b-4b35-a2cf-d1e935e1079a.png)

**Comment by pcislocked** [comment]
please do not use white theme my eyes burned to death while reading it


thanks

also, win-capture-audio works fine on me with 28.0.1. not sure about latest tho, i use it regularly so i cant really update it every time i feel like doing so.

**Comment by PlavorSeol** [comment]
> please do not use white theme my eyes burned to death while reading it

Good for you dude, I will **NEVER, EVER, EVER, EVER** switch to dark mode against my will just because crybabies such as you cry about it.
You are not entitled to force me to only use certain display mode. Note that trying to force me will result in completely opposite situation of what you actually intended.
So what? Cry harder 🤣

**Comment by pcislocked** [comment]
damn

what a child
