### ISSUE TITLE
Capture all audio does not work if the target application is closed

### ISSUE THREAD

**Issue by KaleidonKep99** [bozbez/win-capture-audio#34]
**Plugin version:** v2.0.0-beta.2
I have OBS currently set up like this:
- Source 1 is "Spotify audio output", which only records the output from the target application Spotify.exe
![image](https://user-images.githubusercontent.com/11065274/132262383-3c468170-a338-48e5-ad68-055cd5d01a82.png)

- Source 2 is "Audio output w/o Spotify", which records the entire desktop audio except for Spotify.exe (**Capture all audio EXCEPT the selected window** is enabled)
![image](https://user-images.githubusercontent.com/11065274/132262378-5727abe4-abdd-476d-bd06-2aed39fc5ac1.png)

When the target application is closed, there's no audio in Source 1, but that's okay.
The issue is that there's no audio on Source 2 as well, which is supposed to get the entire desktop audio, even when the target application is closed.

**Comment by bozbez** [comment]
Yeah this is expected with the current architecture, sort of a misword of the option.
But I understand for that option to be useful then you would indeed want it to capture everything when it is unselected...

Might be a bit awkward to implement, need at least to change to using the `IAudioSessionNotification` interface.

**Comment by mil1i** [comment]
Agree on this one. With the "Capture all audio EXCEPT the selected window", it would be great if this audio capture still works even without said selected application open. Otherwise it requires opening say **Spotify** in this example even if you are not using it, or creating separate audio source and manually switching between monitoring when the application is open or closed :\

Just wanted to kind of comment here as a +1, as I don't know the windows api's by your response if the `IAudioSessionNotification` is the fix for this.

**Comment by bozbez** [comment]
Fixed in [v2.2.0-beta](https://github.com/bozbez/win-capture-audio/releases/tag/v2.2.0-beta).
