### ISSUE TITLE
Spams log file and eats CPU time with "audio-capture-helper" after quitting target process

### ISSUE THREAD

**Issue by matoi974** [bozbez/win-capture-audio#38]
I reproduced this with PAYDAY 2 (payday2_win32_release.exe). After quitting it, the win-capture-audio plugin started spawning an executable every 5 seconds and spamming the log file with attempts to capture. I tried reproducing this with foobar2000 (the audio player), and it did not reproduce.
[2021-09-09_15-49-12.txt](https://github.com/bozbez/win-capture-audio/files/7139425/2021-09-09_15-49-12.txt)

**Comment by BuyMyMojo** [comment]
CPU time is just the up time of a process/how long it's been running. that wont cause issues but as a mitigation for the spamming of `(set_update_timer) setting timer for 2000 millis` some what would be to disable attempts to rehook process while in a background scene since it still throws the error even after changing scenes

**Comment by bozbez** [comment]
I wasn't able to reproduce this but there were some issues with the hotkey handling which I suspect might be the cause.
Tried to fix some of these in 06309fffdc387c0e25c051b4f57b00c49e3e2230, so give the latest release a go.

**Comment by bozbez** [comment]
Confirmed fixed.
